# Generated by Django 4.2.3 on 2023-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
