# Generated by Django 4.2.3 on 2023-08-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_category_alter_note_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='name',
        ),
    ]
