# Generated by Django 4.2.3 on 2023-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='undefined', unique=True),
            preserve_default=False,
        ),
    ]
