# Generated by Django 4.2.3 on 2023-08-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_helprequests_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequests',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpRequests', to='notes.note', unique=True),
        ),
    ]
