# Generated by Django 4.2.3 on 2023-09-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_helprequests_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequests',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helpRequests', to='notes.note'),
        ),
    ]
