# Generated by Django 4.2.3 on 2023-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_helprequests_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequests',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='helprequests',
            name='offer',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
